name: Docker Image CI

on:
  push:
    tags:
       - '*'

jobs:
  build:

    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Docker Build
        run: docker build . --cache-from yabramkin/aws-cdk-runtime-environment-win:latest --file Dockerfile --tag yabramkin/aws-cdk-runtime-environment-win:${{steps.tag.outputs.tag}}
      - name: Docker Tag
        run: docker tag yabramkin/aws-cdk-runtime-environment-win:${{steps.tag.outputs.tag}}  yabramkin/aws-cdk-runtime-environment-win:latest
      - name: Docker push version
        run: docker push yabramkin/aws-cdk-runtime-environment-win:${{steps.tag.outputs.tag}}
      - name: Docker push and update latest
        run: docker push yabramkin/aws-cdk-runtime-environment-win:latest
